//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookConnection.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FacebookConnection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This project depends of:
        ///1. Newtonsoft.JSON library..
        /// </summary>
        internal static string Dependences {
            get {
                return ResourceManager.GetString("Dependences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mzMhW7mUU0lI6xaAWAm5ZzTOfQ/0RlHk61zH5435Yk/j7fSoHE0g9DckeIG3l8rsGsxcI9V5/hXHtblua6RxLIZWU4hUn5yWXXAniON9G4vaHGZYNGAbsGzG+idnt0vU9HfdnCthgbXp8kp2gm3ZIism6Pj1VNH4x7Rgp22dF40z/Oem6cHNn2xvkJHq6LhPYa4intUEvdn+ZdSEhMNkTl+PBisuBZX0MT9FWGMkUR3onvi2t7BuTzQwpqCXGfb3AChYBd1bcsHy3Z8Y9YabS9e8YRZDEAl8LCRyTnjkrImYZG3P1vkc3wd3MnUs0nju6yY5a8YCmjXE+KmmyxQ4azMSxmRj4RV+afkZi+53IMuJ7Dord9gNqheHj/oUbBLg3oeseFO88dkaCck+2ojc0bNPQOM1tb4NPwJV8sqM0CPfWv3rAUQiQw==
        ///.
        /// </summary>
        internal static string FacebookCredentials {
            get {
                return ResourceManager.GetString("FacebookCredentials", resourceCulture);
            }
        }
    }
}
